### ISSUE TITLE
from_date argument in get_eod_historical_stock_market_data doesn't work

### ISSUE THREAD

**Issue by MislavSag** [EodHistoricalData/EODHD-APIs-R-Financial-Library#5]
Hi,

I have just bought full API subscription for one month to test it.

Hope to migrate from current provider:)

I have tested EOS data:
```
eod_l = get_eod_historical_stock_market_data(
    api_token = APIKEY, 
    symbol = "AAPL.US", 
    from_date = "2000-01-01", 
    to_date = "2023-06-01"
)
```
For me, this returns data from 1980-12-12, even if I set `from_date = "2000-01-01",`

**Comment by Nawado** [comment]
Thanks for your feedback. We will fix this bug in the next version. At the moment, this library is under active development and we will try to supplement it as quickly as possible. I can also offer a Python library with similar functions: https://github.com/EodHistoricalData/EODHD-APIs-Python-Financial-Library

**Comment by Nawado** [comment]
This function can also be used in the new version. Dates must be determined correctly

**Comment by Nawado** [comment]
This problem has been fixed in the new version of the library.
